// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZs25Z6B4BuDn5yAWfjQDUa11Bx05U0TM',
    appId: '1:879917390100:android:af99c8e1d48085bcd94a01',
    messagingSenderId: '879917390100',
    projectId: 'todoappfluttersession',
    databaseURL: 'https://todoappfluttersession-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todoappfluttersession.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChZETLutLYPG68Kx5F9Dra_RUZLxiIhVI',
    appId: '1:879917390100:ios:437b54227c5219d7d94a01',
    messagingSenderId: '879917390100',
    projectId: 'todoappfluttersession',
    databaseURL: 'https://todoappfluttersession-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todoappfluttersession.appspot.com',
    iosClientId: '879917390100-gplk0gi1nnj3gpv446qfj1hm3tib3n3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInterviewTest',
  );
}
